/**
 * 54 dân tộc Việt Nam chính thức (theo Tổng cục Thống kê) + "Khác"
 * Sắp xếp theo tên tiếng Việt, "Kinh" đặt đầu tiên vì chiếm ~86% dân số.
 */
import type { ComboboxOption } from "~/components/ui/form-combobox";

export const ETHNICITIES: ComboboxOption[] = [
  { value: "Kinh", label: "Kinh" },
  { value: "Ba Na", label: "Ba Na" },
  { value: "Bố Y", label: "Bố Y" },
  { value: "Brâu", label: "Brâu" },
  { value: "Bru - Vân Kiều", label: "Bru - Vân Kiều" },
  { value: "Chăm", label: "Chăm" },
  { value: "Cho Ro", label: "Cho Ro" },
  { value: "Chơ Ro", label: "Chơ Ro" },
  { value: "Chứt", label: "Chứt" },
  { value: "Co", label: "Co" },
  { value: "Cờ Ho", label: "Cờ Ho" },
  { value: "Cờ Lao", label: "Cờ Lao" },
  { value: "Cờ Tu", label: "Cờ Tu" },
  { value: "Cống", label: "Cống" },
  { value: "Dao", label: "Dao" },
  { value: "Ê Đê", label: "Ê Đê" },
  { value: "Gia Rai", label: "Gia Rai" },
  { value: "Giáy", label: "Giáy" },
  { value: "Giẻ Triêng", label: "Giẻ Triêng" },
  { value: "Hà Nhì", label: "Hà Nhì" },
  { value: "Hmông", label: "Hmông" },
  { value: "Hoa", label: "Hoa" },
  { value: "Hrê", label: "Hrê" },
  { value: "Kháng", label: "Kháng" },
  { value: "Khmer", label: "Khmer" },
  { value: "Khơ Mú", label: "Khơ Mú" },
  { value: "La Chí", label: "La Chí" },
  { value: "La Ha", label: "La Ha" },
  { value: "La Hủ", label: "La Hủ" },
  { value: "Lào", label: "Lào" },
  { value: "Lô Lô", label: "Lô Lô" },
  { value: "Lự", label: "Lự" },
  { value: "Ma", label: "Ma" },
  { value: "Mảng", label: "Mảng" },
  { value: "Mnông", label: "Mnông" },
  { value: "Mường", label: "Mường" },
  { value: "Ngái", label: "Ngái" },
  { value: "Nùng", label: "Nùng" },
  { value: "Ơ Đu", label: "Ơ Đu" },
  { value: "Pà Thẻn", label: "Pà Thẻn" },
  { value: "Phù Lá", label: "Phù Lá" },
  { value: "Pu Péo", label: "Pu Péo" },
  { value: "Ra Glai", label: "Ra Glai" },
  { value: "Rơ Măm", label: "Rơ Măm" },
  { value: "Sán Chay", label: "Sán Chay" },
  { value: "Sán Dìu", label: "Sán Dìu" },
  { value: "Si La", label: "Si La" },
  { value: "Tà Ôi", label: "Tà Ôi" },
  { value: "Tày", label: "Tày" },
  { value: "Thái", label: "Thái" },
  { value: "Thổ", label: "Thổ" },
  { value: "Xinh Mun", label: "Xinh Mun" },
  { value: "Xơ Đăng", label: "Xơ Đăng" },
  { value: "Xtiêng", label: "Xtiêng" },
  { value: "Khác", label: "Khác" },
];
